services:
  mariadb:
    build: requirements/database
    container_name: mariadb
    restart: unless-stopped
    env_file: .env
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - inception
    healthcheck:
      test: ["CMD", "mariadb-admin", "ping", "-h", "localhost", "-u", "health", "-phealth", "--skip-ssl"]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 10s
    labels:
      glance.parent: wp
      glance.name: Database

  wordpress:
    build: requirements/wordpress
    container_name: wordpress
    restart: unless-stopped
    env_file: .env
    depends_on:
      mariadb:
        condition: service_healthy
      redis:
        condition: service_started
    volumes:
      - wp-data:/var/www/html
      - shared-config:/shared
    networks:
      - inception
    labels:
      glance.name: Wordpress
      glance.icon: si:wordpress
      glance.url: https://${DOMAIN_NAME}
      glance.description: Wordpress Site
      glance.id: wp
  
  nginx:
    build: requirements/nginx
    container_name: nginx
    restart: unless-stopped
    env_file : .env
    ports:
      - "443:443"
    networks:
      - inception
    depends_on:
      - wordpress
      - adminer
    volumes:
      - wp-data:/var/www/html
    labels:
      glance.name: Nginx
      glance.icon: si:nginx
      glance.description: Nginx server
      glance.id: nginx
  
  # ------ bonus ------

  redis:
    build: bonus/redis
    container_name: redis
    restart: unless-stopped
    env_file: .env
    ports:
      - "6379:6379"
    networks:
      - inception
    labels:
      glance.name: Redis
      glance.parent: wp
  
  adminer:
    build: bonus/adminer
    container_name: adminer
    restart: unless-stopped
    ports:
      - "8080:8080"
    depends_on:
      mariadb:
         condition: service_healthy
    networks:
      - inception
    labels:
      glance.name: Adminer
      glance.icon: si:adminer
      glance.url: https://${DOMAIN_NAME}/adminer
      glance.description: Administration service
      glance.id: adminer
    
  ftp:
    build: bonus/ftp
    container_name: ftp
    restart: unless-stopped
    env_file: .env
    volumes:
     - wp-data:/var/www/html
    ports: 
      - "21:21"
      - "21210-21220:21210-21220"
    networks:
     - inception
    labels:
      glance.name: Vsftp
      glance.icon: si:filezilla
      glance.description: Vsftp server
      glance.id: vsftp

  static_page:
    build: bonus/static_page
    container_name: static_page
    restart: unless-stopped
    env_file: .env
    networks:
     - inception
    labels:
      glance.name: Welcome Page
      glance.icon: si:wikipedia
      glance.url:  https://${DOMAIN_NAME}/welcome
      glance.description: A simple static page
      glance.id: static

  glance:
    container_name: glance
    build : bonus/glance
    restart: unless-stopped
    volumes :
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - inception
    ports :
      - "8081:8081"
    env_file : .env
    labels:
      glance.icon: si:glance
      glance.description: A dashboard manager
      glance.name: Glance

networks:
  inception:
    name: inception
    driver: bridge

volumes:
  db-data :
    driver: local
    driver_opts:
       o: bind
       type: none
       device: ${DATA_PATH}/data/db-data

  wp-data:
    driver: local
    driver_opts:
       o: bind
       type: none
       device: ${DATA_PATH}/data/wp-data
  
  shared-config:
    driver: local
